version: '3.8'

services:
  fpm:
    container_name: rally_php
    environment:
      - MYSQL_HOST=$MYSQL_HOST
    build:
      args:
        SECRET_DIR: $SECRET_DIR
      context: $VOLUME_BASE_DIR
      dockerfile: $VOLUME_BASE_DIR/deploy/php/Dockerfile
    volumes:
      - $VOLUME_BASE_DIR:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db

  nginx:
    container_name: rally_nginx
    build:
      dockerfile: $VOLUME_BASE_DIR/deploy/nginx/Dockerfile
      context: $VOLUME_BASE_DIR
    ports:
      - "8888:8080"
    volumes:
      - $VOLUME_BASE_DIR:/var/www/html
    restart: on-failure
    depends_on:
      - fpm

  db:
    image: mariadb:10.6.7
    container_name: rally_db
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
    restart: on-failure
